"use client";

import React from "react";

interface ParameterRow {
  name: string;
  type: string;
  required: boolean;
  description: string;
}

const PARAMETERS: ParameterRow[] = [
  {
    name: "url",
    type: "string",
    required: true,
    description: "The raw target URL string to be shortened and persisted into PostgreSQL (e.g. https://github.com).",
  },
  {
    name: "id",
    type: "string (path)",
    required: true,
    description: "The unique Base58 hash identifier generated by the Echo backend for URL redirection.",
  },
  {
    name: "delay",
    type: "integer (sec)",
    required: false,
    description: "Seconds Keploy waits before dispatching replay requests during test mode (defaults to 10s).",
  },
  {
    name: "api-key",
    type: "string (secret)",
    required: false,
    description: "Your Keploy cloud authentication key (kep_XXXX) for storing centralized mocks and generating reports.",
  },
  {
    name: "mocks.yaml",
    type: "artifact (yaml)",
    required: true,
    description: "Auto-generated wire-level PostgreSQL packets capturing all SQL handshake and query cycles.",
  },
];

export function ParametersTable() {
  return (
    <div className="my-8 space-y-3">
      <div className="flex items-center justify-between">
        <h3 className="text-lg font-bold text-slate-900 dark:text-slate-100">
          Request Parameters &amp; Test Artifacts
        </h3>
        <span className="text-xs text-slate-500 font-mono">schema v1beta1</span>
      </div>
      <p className="text-sm text-slate-600 dark:text-slate-400">
        The Echo URL-shortener endpoint and Keploy recording harness use the following schema structure:
      </p>

      <div className="overflow-x-auto rounded-xl border border-slate-200 dark:border-slate-800 bg-white dark:bg-[#0d111c] shadow-sm">
        <table className="w-full text-left text-xs md:text-sm">
          <thead>
            <tr className="border-b border-slate-200 dark:border-slate-800 bg-slate-50 dark:bg-[#141926] text-slate-700 dark:text-slate-300 font-mono text-[11px] uppercase tracking-wider">
              <th className="py-3 px-4">Parameter</th>
              <th className="py-3 px-4">Type</th>
              <th className="py-3 px-4">Requirement</th>
              <th className="py-3 px-4">Description</th>
            </tr>
          </thead>
          <tbody className="divide-y divide-slate-100 dark:divide-slate-800/60 font-sans">
            {PARAMETERS.map((row, idx) => (
              <tr
                key={idx}
                className="hover:bg-slate-50/60 dark:hover:bg-slate-800/30 transition-colors"
              >
                <td className="py-3.5 px-4 font-mono font-semibold text-indigo-600 dark:text-indigo-400">
                  {row.name}
                </td>
                <td className="py-3.5 px-4">
                  <span className="px-2 py-0.5 rounded bg-slate-100 dark:bg-slate-800 text-slate-700 dark:text-slate-300 font-mono text-xs">
                    {row.type}
                  </span>
                </td>
                <td className="py-3.5 px-4">
                  {row.required ? (
                    <span className="px-2 py-0.5 rounded text-[11px] font-bold uppercase tracking-wider bg-rose-500/10 text-rose-600 dark:text-rose-400 border border-rose-500/20">
                      required
                    </span>
                  ) : (
                    <span className="px-2 py-0.5 rounded text-[11px] font-medium text-slate-500 bg-slate-100 dark:bg-slate-800">
                      optional
                    </span>
                  )}
                </td>
                <td className="py-3.5 px-4 text-slate-600 dark:text-slate-300 text-xs md:text-sm leading-relaxed">
                  {row.description}
                </td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
    </div>
  );
}
